# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  workflow_dispatch:
   

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    uses: bbq-beets/cschleiden-lab/.github/workflows/test.yml@master
